/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1v2;

import javax.swing.JOptionPane;

/**
 *
 * @author Mynor Escobar
 */
public class SelectorDePersonaje extends javax.swing.JFrame {

    /**
     * Creates new form SelectorDePersonaje
     */
    public SelectorDePersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblimgjugador1 = new javax.swing.JLabel();
        lblimgjugador2 = new javax.swing.JLabel();
        lblimgjugador3 = new javax.swing.JLabel();
        lblimgjugador4 = new javax.swing.JLabel();
        lblimgjugador5 = new javax.swing.JLabel();
        lblimgjugador6 = new javax.swing.JLabel();
        lblinstrucciones = new javax.swing.JLabel();
        lblturno1jugador1 = new javax.swing.JLabel();
        lblturno2jugador1 = new javax.swing.JLabel();
        lblturno3jugador1 = new javax.swing.JLabel();
        lblturno1jugador2 = new javax.swing.JLabel();
        lblturno2jugador2 = new javax.swing.JLabel();
        lblturno3jugador2 = new javax.swing.JLabel();
        txtturno1jugador1 = new javax.swing.JTextField();
        txtturno2jugador1 = new javax.swing.JTextField();
        txtturno3jugador1 = new javax.swing.JTextField();
        txtturno1jugador2 = new javax.swing.JTextField();
        txtturno2jugador2 = new javax.swing.JTextField();
        txtturno3jugador2 = new javax.swing.JTextField();
        lblinstruccionestamano = new javax.swing.JLabel();
        txttamanocuadricula = new javax.swing.JTextField();
        btnjugar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbltitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltitulo.setText("¡Prepara el orden para la Batalla!");

        lblimgjugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mago1.jpg"))); // NOI18N

        lblimgjugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/princesa1.jpg"))); // NOI18N

        lblimgjugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guerrero1.jpg"))); // NOI18N

        lblimgjugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mago2.jpg"))); // NOI18N

        lblimgjugador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/princesa2.jpg"))); // NOI18N

        lblimgjugador6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guerrero2.jpg"))); // NOI18N

        lblinstrucciones.setText("Escoge a tu personaje en el orden en que peleará. Escribe el numero en la casilla ya sea 1: Mago, 2: Princesa, 3: Guerrero");

        lblturno1jugador1.setText("Turno 1:");

        lblturno2jugador1.setText("Turno 2:");

        lblturno3jugador1.setText("Turno 3:");

        lblturno1jugador2.setText("Turno 1:");

        lblturno2jugador2.setText("Turno 2:");

        lblturno3jugador2.setText("Turno 3:");

        txtturno1jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno1jugador1ActionPerformed(evt);
            }
        });

        txtturno2jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno2jugador1ActionPerformed(evt);
            }
        });

        txtturno3jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno3jugador1ActionPerformed(evt);
            }
        });

        txtturno1jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno1jugador2ActionPerformed(evt);
            }
        });

        txtturno2jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno2jugador2ActionPerformed(evt);
            }
        });

        txtturno3jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtturno3jugador2ActionPerformed(evt);
            }
        });

        lblinstruccionestamano.setText("Digita el tamaño del tablero, minimo 8 maximo 18. Será tamañoXtamaño:");

        txttamanocuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttamanocuadriculaActionPerformed(evt);
            }
        });

        btnjugar.setText("A jugar bro!");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblturno3jugador1)
                                .addGap(18, 18, 18)
                                .addComponent(txtturno3jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(390, 390, 390)
                                .addComponent(txtturno3jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblturno2jugador1)
                                .addGap(18, 18, 18)
                                .addComponent(txtturno2jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(390, 390, 390)
                                .addComponent(txtturno2jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblimgjugador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblinstrucciones)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblimgjugador2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblimgjugador3)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblimgjugador4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblimgjugador5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblimgjugador6)))))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblturno1jugador1)
                                .addGap(18, 18, 18)
                                .addComponent(txtturno1jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblturno1jugador2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblturno3jugador2)
                                    .addComponent(lblturno2jugador2))))
                        .addGap(18, 18, 18)
                        .addComponent(txtturno1jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnjugar)
                                .addGap(215, 215, 215)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblinstruccionestamano)
                                .addGap(18, 18, 18)
                                .addComponent(txttamanocuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimgjugador1)
                    .addComponent(lblimgjugador2)
                    .addComponent(lblimgjugador3)
                    .addComponent(lblimgjugador4)
                    .addComponent(lblimgjugador5)
                    .addComponent(lblimgjugador6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinstrucciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblturno1jugador1)
                    .addComponent(lblturno1jugador2)
                    .addComponent(txtturno1jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtturno1jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblturno2jugador1)
                    .addComponent(lblturno2jugador2)
                    .addComponent(txtturno2jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtturno2jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblturno3jugador1)
                    .addComponent(lblturno3jugador2)
                    .addComponent(txtturno3jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtturno3jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinstruccionestamano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttamanocuadricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjugar)
                    .addComponent(btnsalir))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtturno2jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno2jugador1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtturno2jugador1ActionPerformed

    private void txtturno1jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno1jugador1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtturno1jugador1ActionPerformed

    private void txtturno3jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno3jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtturno3jugador1ActionPerformed

    private void txtturno1jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno1jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtturno1jugador2ActionPerformed

    private void txtturno2jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno2jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtturno2jugador2ActionPerformed

    private void txtturno3jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtturno3jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtturno3jugador2ActionPerformed

    private void txttamanocuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttamanocuadriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttamanocuadriculaActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        // TODO add your handling code here:
        
        /*if(txtturno1jugador1.getText().equalsIgnoreCase(txtturno2jugador1.getText()) || txtturno1jugador1.getText().equalsIgnoreCase(txtturno3jugador1.getText())
                ||txtturno2jugador1.getText().equalsIgnoreCase(txtturno3jugador1.getText())){
            
            JOptionPane.showMessageDialog(null, "Revisa las casillas de turno, por favor");
            
        }*/
        //ESTABLECIENDO TURNOS JUGADOR 1
        this.estableceTurno1Jug1();
        this.estableceTurno2Jug1();
        this.estableceTurno3Jug1();
        
        //ESTABLECIENDO TURNOS JUGADOR 2
        this.estableceTurno1Jug2();
        this.estableceTurno2Jug2();
        this.estableceTurno3Jug2();
        
        //TAMAÑO DE LA CUADRICULA
        this.estableceTamanoCuadricula();
        
        
        if( (turno1jug1>0 && turno1jug1<4) && (turno2jug1>0 && turno2jug1<4) && (turno3jug1>0 && turno3jug1<4)&&
                (turno1jug2>0 && turno1jug2<4) && (turno2jug2>0 && turno2jug2<4) && (turno3jug2>0 && turno3jug2<4)){
            
            if( ((turno1jug1!=turno2jug1)&&(turno1jug1!=turno3jug1)&&(turno2jug1!=turno3jug1))&&(
                    (turno1jug2!=turno2jug2)&&(turno1jug2!=turno3jug2)&&(turno2jug2!=turno3jug2))){
                
                if(verificadorcuadricula){
                    
                    VentanaDeJuego miventanadejuego = new VentanaDeJuego();
                    miventanadejuego.estableceNombreJugador1(this.dameNombreJugador1());
                    miventanadejuego.estableceNombreJugador2(this.dameNombreJugador2());
                    miventanadejuego.estableceTurno1Jug1(this.dameTurno1Jug1());
                    miventanadejuego.estableceTurno1Jug2(this.dameTurno1Jug2());
                    miventanadejuego.estableceTurno2Jug1(this.dameTurno2Jug1());
                    miventanadejuego.estableceTurno2Jug2(this.dameTurno2Jug2());
                    miventanadejuego.estableceTurno3Jug1(this.dameTurno3Jug1());
                    miventanadejuego.estableceTurno3Jug2(this.dameTurno3Jug2());
                    miventanadejuego.estableceTamanoCuadricula(this.dameTamanoCuadricula());
                    miventanadejuego.estableceCuadriculaVisible();
                    miventanadejuego.setLocationRelativeTo(null);
                    this.setVisible(false);
                    miventanadejuego.setVisible(true);
                    
                }
                
            } else {
                
                JOptionPane.showMessageDialog(null, "No puedes elegir al mismo jugador, selecciona numeros diferentes"
                        + " en las casillas de los turnos");
                
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Verifica que en casilla de turnos este unicamente del 1 al 3");
            
        }
        
    }//GEN-LAST:event_btnjugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorDePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorDePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorDePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorDePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorDePersonaje().setVisible(true);
            }
        });
    }
    
    //METODOS PARA TURNOS
        //JUGADOR1
    public void estableceTurno1Jug1(){//SETTER
        
        try{
            
            turno1jug1 = Integer.parseInt(txtturno1jugador1.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 1 del Jugador 1");
            turno1jug1 = 0;
        }
        
    }
    
    public int dameTurno1Jug1(){//GETTER
        
        return turno1jug1;
        
    }
    public void estableceTurno2Jug1(){//SETTER
        
        try{
            
            turno2jug1 = Integer.parseInt(txtturno2jugador1.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 2 del Jugador 1");
            turno2jug1 = 0;
                        
        }
        
    }
    public int dameTurno2Jug1(){//GETTER
        
        return turno2jug1;
        
    }
    public void estableceTurno3Jug1(){//SETTER
        
        try{
            
            turno3jug1 = Integer.parseInt(txtturno3jugador1.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 3 del Jugador 1");
            turno3jug1 = 0;
            
        }
        
    }
    public int dameTurno3Jug1(){
        
        return turno3jug1;
        
    }
        //JUGADOR 2
    public void estableceTurno1Jug2(){//SETTER
        
        try{
            
            turno1jug2 = Integer.parseInt(txtturno1jugador2.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 1 del Jugador 2");
            turno1jug2 = 0;
        }
        
    }
    
    public int dameTurno1Jug2(){//GETTER
        
        return turno1jug2;
        
    }
    public void estableceTurno2Jug2(){//SETTER
        
        try{
            
            turno2jug2 = Integer.parseInt(txtturno2jugador2.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 2 del Jugador 2");
            turno2jug2 = 0;
        }
        
    }
    public int dameTurno2Jug2(){//GETTER
        
        return turno2jug2;
        
    }
    public void estableceTurno3Jug2(){//SETTER
        
        try{
            
            turno3jug2 = Integer.parseInt(txtturno3jugador2.getText());
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Ingresa un numero, por favor en: Turno 3 del Jugador 2");
            turno3jug2 = 0;
        }
        
    }
    public int dameTurno3Jug2(){
        
        return turno3jug2;
        
    }
    
    public void estableceNombreJugador1(String nom){//SETTER NOMBRE JUGADOR 1
        
        nombrejugador1 = nom;
        
    }
    
    public String dameNombreJugador1(){//GETTER NOMBRE JUGADOR1
        
        return nombrejugador1;
        
    }
    
    public void estableceNombreJugador2(String nom){//SETTER NOMBRE JUGADOR 2
        
        nombrejugador2 = nom;
        
    }
    
    public String dameNombreJugador2(){//GETTER NOMBRE JUGADOR 2
        
        return nombrejugador2;
        
    }
    
    public void estableceTamanoCuadricula(){
        
        try{
            
            if((Integer.parseInt(txttamanocuadricula.getText())>7) && (Integer.parseInt(txttamanocuadricula.getText())<19)){
                
                tamanocuadricula = Integer.parseInt(txttamanocuadricula.getText());
                verificadorcuadricula = true;
                
            } else {
                
                JOptionPane.showMessageDialog(null, "El tamaño de la cuadrícula debe estar entre 8 y 18 únicamente");
                verificadorcuadricula = false;
                
            }
            
        } catch (java.lang.NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Verifica que el tamaño de la cuadricula sea un número");
            
        }
        
        
    }
    public int dameTamanoCuadricula(){
        
        return tamanocuadricula;
        
    }
    
    
    //VARIABLES PARA TURNOS
    private String nombrejugador1;
    private int turno1jug1;
    private int turno2jug1;
    private int turno3jug1;
    
    private String nombrejugador2;
    private int turno1jug2;
    private int turno2jug2;
    private int turno3jug2;
    
    //TAMAÑO DE CUADRICULA
    private int tamanocuadricula;
    private boolean verificadorcuadricula;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel lblimgjugador1;
    private javax.swing.JLabel lblimgjugador2;
    private javax.swing.JLabel lblimgjugador3;
    private javax.swing.JLabel lblimgjugador4;
    private javax.swing.JLabel lblimgjugador5;
    private javax.swing.JLabel lblimgjugador6;
    private javax.swing.JLabel lblinstrucciones;
    private javax.swing.JLabel lblinstruccionestamano;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblturno1jugador1;
    private javax.swing.JLabel lblturno1jugador2;
    private javax.swing.JLabel lblturno2jugador1;
    private javax.swing.JLabel lblturno2jugador2;
    private javax.swing.JLabel lblturno3jugador1;
    private javax.swing.JLabel lblturno3jugador2;
    private javax.swing.JTextField txttamanocuadricula;
    private javax.swing.JTextField txtturno1jugador1;
    private javax.swing.JTextField txtturno1jugador2;
    private javax.swing.JTextField txtturno2jugador1;
    private javax.swing.JTextField txtturno2jugador2;
    private javax.swing.JTextField txtturno3jugador1;
    private javax.swing.JTextField txtturno3jugador2;
    // End of variables declaration//GEN-END:variables
}
