/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1v2;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Mynor Escobar
 */
public class VentanaDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDeJuego
     */
    public VentanaDeJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuadricula = new javax.swing.JPanel();
        lbletiquetanombre1 = new javax.swing.JLabel();
        lblnombrejugador1 = new javax.swing.JLabel();
        lbletiquetapersonajes1 = new javax.swing.JLabel();
        lblturno1jug1 = new javax.swing.JLabel();
        lblturno2jug1 = new javax.swing.JLabel();
        lblturno3jug1 = new javax.swing.JLabel();
        lbletiquetanombre2 = new javax.swing.JLabel();
        lblnombrejugador2 = new javax.swing.JLabel();
        lbletiquetapersonajes2 = new javax.swing.JLabel();
        lblturno1jug2 = new javax.swing.JLabel();
        lblturno2jug2 = new javax.swing.JLabel();
        lblturno3jug2 = new javax.swing.JLabel();
        fondovidas1 = new javax.swing.JPanel();
        fondovidas2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbldado = new javax.swing.JLabel();
        btntirar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnarriba = new javax.swing.JButton();
        btnabajo = new javax.swing.JButton();
        btnderecha = new javax.swing.JButton();
        btnizquierda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batallando Medievalmente");
        setResizable(false);

        javax.swing.GroupLayout cuadriculaLayout = new javax.swing.GroupLayout(cuadricula);
        cuadricula.setLayout(cuadriculaLayout);
        cuadriculaLayout.setHorizontalGroup(
            cuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        cuadriculaLayout.setVerticalGroup(
            cuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        lbletiquetanombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbletiquetanombre1.setText("Jugador 1:");

        lblnombrejugador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnombrejugador1.setText("jLabel1");

        lbletiquetapersonajes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbletiquetapersonajes1.setText("Personajes");

        lblturno1jug1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno1jug1.setText("Guerrero");

        lblturno2jug1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno2jug1.setText("Guerrero");

        lblturno3jug1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno3jug1.setText("Guerrero");

        lbletiquetanombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbletiquetanombre2.setText("Jugador 2:");

        lblnombrejugador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnombrejugador2.setText("jLabel1");

        lbletiquetapersonajes2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbletiquetapersonajes2.setText("Personajes");

        lblturno1jug2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno1jug2.setText("Guerrero");

        lblturno2jug2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno2jug2.setText("Guerrero");

        lblturno3jug2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblturno3jug2.setText("Guerrero");

        javax.swing.GroupLayout fondovidas1Layout = new javax.swing.GroupLayout(fondovidas1);
        fondovidas1.setLayout(fondovidas1Layout);
        fondovidas1Layout.setHorizontalGroup(
            fondovidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        fondovidas1Layout.setVerticalGroup(
            fondovidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondovidas2Layout = new javax.swing.GroupLayout(fondovidas2);
        fondovidas2.setLayout(fondovidas2Layout);
        fondovidas2Layout.setHorizontalGroup(
            fondovidas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        fondovidas2Layout.setVerticalGroup(
            fondovidas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        lbldado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.gif"))); // NOI18N

        btntirar.setText("Detener");
        btntirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntirarActionPerformed(evt);
            }
        });

        btnarriba.setText("↑");
        btnarriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarribaActionPerformed(evt);
            }
        });

        btnabajo.setText("↓");
        btnabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabajoActionPerformed(evt);
            }
        });

        btnderecha.setText("→");
        btnderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderechaActionPerformed(evt);
            }
        });

        btnizquierda.setText("←");
        btnizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizquierdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnabajo)
                    .addComponent(btnarriba))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnizquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnderecha))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnarriba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbletiquetanombre2)
                                .addGap(18, 18, 18)
                                .addComponent(lblnombrejugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fondovidas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbletiquetapersonajes2)
                                .addGap(2, 2, 2))
                            .addComponent(lblturno1jug2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblturno2jug2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblturno3jug2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbletiquetanombre1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblnombrejugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(fondovidas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbletiquetapersonajes1)
                                        .addGap(2, 2, 2))
                                    .addComponent(lblturno1jug1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblturno2jug1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblturno3jug1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldado)
                                .addGap(2, 2, 2)
                                .addComponent(btntirar)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbletiquetanombre1)
                            .addComponent(lblnombrejugador1)
                            .addComponent(lbletiquetapersonajes1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fondovidas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblturno1jug1)
                                .addGap(18, 18, 18)
                                .addComponent(lblturno2jug1)
                                .addGap(18, 18, 18)
                                .addComponent(lblturno3jug1)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbletiquetanombre2)
                            .addComponent(lblnombrejugador2)
                            .addComponent(lbletiquetapersonajes2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblturno1jug2)
                                .addGap(18, 18, 18)
                                .addComponent(lblturno2jug2)
                                .addGap(18, 18, 18)
                                .addComponent(lblturno3jug2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fondovidas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btntirar)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldado)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderechaActionPerformed
        // TODO add your handling code here:
        
        Movimiento mov = new Movimiento(numerodedado, tablero, "derecha");
        mov.start();
        lbldado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.gif")));
        
    }//GEN-LAST:event_btnderechaActionPerformed

    private void btntirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntirarActionPerformed
        // TODO add your handling code here:
        
        boolean numeroobtenido = true;
        while(numeroobtenido){
            
            numerodedado = (int)(Math.random()*100);
            if(numerodedado>0 && numerodedado<7){
                
                numeroobtenido = false;
                switch(numerodedado){
                    
                    case 1:
                        
                        ImageIcon dado1temp = new ImageIcon(getClass().getResource("/Imagenes/1.jpg"));
                        Image dado1 = dado1temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado1);
                        lbldado.setIcon(dado);
                        break;
                        
                    case 2:
                        
                        ImageIcon dado2temp = new ImageIcon(getClass().getResource("/Imagenes/2.jpg"));
                        Image dado2 = dado2temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado2);
                        lbldado.setIcon(dado);
                        break;
                        
                    case 3:
                        
                        ImageIcon dado3temp = new ImageIcon(getClass().getResource("/Imagenes/3.jpg"));
                        Image dado3 = dado3temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado3);
                        lbldado.setIcon(dado);
                        break;
                    
                    case 4:
                        
                        ImageIcon dado4temp = new ImageIcon(getClass().getResource("/Imagenes/4.jpg"));
                        Image dado4 = dado4temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado4);
                        lbldado.setIcon(dado);
                        break;
                        
                    case 5:
                        
                        ImageIcon dado5temp = new ImageIcon(getClass().getResource("/Imagenes/5.jpg"));
                        Image dado5 = dado5temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado5);
                        lbldado.setIcon(dado);
                        break;
                        
                    case 6:
                        
                        ImageIcon dado6temp = new ImageIcon(getClass().getResource("/Imagenes/6.jpg"));
                        Image dado6 = dado6temp.getImage().getScaledInstance(64, 61, Image.SCALE_SMOOTH);
                        dado = new ImageIcon(dado6);
                        lbldado.setIcon(dado);
                        break;
                    
                }
                
            }
            
        }
                
    }//GEN-LAST:event_btntirarActionPerformed

    private void btnizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizquierdaActionPerformed
        // TODO add your handling code here:
        
        Movimiento mov = new Movimiento(numerodedado, tablero, "izquierda");
        mov.start();
        lbldado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.gif")));
        
    }//GEN-LAST:event_btnizquierdaActionPerformed

    private void btnabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabajoActionPerformed
        // TODO add your handling code here:
        
        Movimiento mov = new Movimiento(numerodedado, tablero, "abajo");
        mov.start();
        lbldado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.gif")));
        
    }//GEN-LAST:event_btnabajoActionPerformed

    private void btnarribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarribaActionPerformed
        // TODO add your handling code here:
        
        Movimiento mov = new Movimiento(numerodedado, tablero, "arriba");
        mov.start();
        lbldado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado.gif")));
        
    }//GEN-LAST:event_btnarribaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDeJuego().setVisible(true);
            }
        });
    }
    
    public void estableceNombreJugador1(String nom){//SETTER NOMBRE JUGADOR 1
        
        nombrejugador1 = nom;
        lblnombrejugador1.setText(nom);
        
    }
    public String dameNombreJugador1(){//GETTER NOMBRE JUGADOR 1
        
        return nombrejugador1;
        
    }
    public void estableceNombreJugador2(String nom){//SETTER NOMBRE JUGADOR 2
        
        nombrejugador2 = nom;
        lblnombrejugador2.setText(nom);
        
    }
    public String dameNombreJugador2(){//GETTER NOMBRE JUGADOR 2
        
        return nombrejugador2;
        
    }
    //ESTABLECIENDO TURNOS PARA PERSONAJES
    //PARA JUGADOR 1
    public void estableceTurno1Jug1(int personaje){//SETTER DE TURNO 1 JUG 1
        
        turno1jug1 = personaje;
        
    }
    public int dameTurno1Jug1(){//GETTER DE TURNO 1 JUG 1
        
        return turno1jug1;
        
    }
    public void estableceTurno2Jug1(int personaje){//SETTER DE TURNO 2 JUG 1
        
        turno2jug1 = personaje;
        
    }
    public int dameTurno2Jug1(){//GETTER DE TURNO 2 JUG 1
        
        return turno2jug1;
        
    }
    public void estableceTurno3Jug1(int personaje){//SETTER DE TURNO 3 JUG 1
        
        turno3jug1 = personaje;
        
    }
    public int dameTurno3Jug1(){//GETTER DE TURNO 3 JUG 1
        
        return turno2jug1;
        
    }
    
    //PARA JUGADOR 2
    public void estableceTurno1Jug2(int personaje){//SETTER DE TURNO 1 JUG 2
        
        turno1jug2 = personaje;
        
    }
    public int dameTurno1Jug2(){//GETTER DE TURNO 1 JUG 2
        
        return turno1jug2;
        
    }
    public void estableceTurno2Jug2(int personaje){//SETTER DE TURNO 2 JUG 2
        
        turno2jug2 = personaje;
        
    }
    public int dameTurno2Jug2(){//GETTER DE TURNO 2 JUG 2
        
        return turno2jug2;
        
    }
    public void estableceTurno3Jug2(int personaje){//SETTER DE TURNO 3 JUG 2
        
        turno3jug2 = personaje;
        
    }
    public int dameTurno3Jug2(){//GETTER DE TURNO 3 JUG 2
        
        return turno3jug2;
        
    }
    public void estableceTamanoCuadricula(int tamano){//SETTER DEL TAMAÑO DE LA CUADRICULA
        
        tamanocuadricula = tamano;
        
    }
    public int dameTamanoCuadricula(){//GETTER DEL TAMAÑO DE LA CUADRICULA
        
        return tamanocuadricula;
        
    }
    public void estableceCuadriculaVisible(){//ESTABLECE TABLERO Y JUGADORES
        
        cuadricula.removeAll();
        cuadricula.repaint();
        tablero = new Tablero(tamanocuadricula, cuadricula);
        
    }
    
    //NOMBRES DE JUGADORES
    private String nombrejugador1;
    private String nombrejugador2;
    
    //TURNOS JUGADOR 1 (#1 para mago, #2 para princesa, #3 para guerrero)
    private int turno1jug1;
    private int turno2jug1;
    private int turno3jug1;
    
    //TURNOS JUGADOR 2 (#1 para mago, #2 para princesa, #3 para guerrero)
    private int turno1jug2;
    private int turno2jug2;
    private int turno3jug2;
    
    //TAMAÑO PARA LA CUADRICULA
    private int tamanocuadricula;
    
    //DECLARACION DE TABLERO
    private Tablero tablero;
    
    private int numerodedado;
    private ImageIcon dado;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabajo;
    private javax.swing.JButton btnarriba;
    private javax.swing.JButton btnderecha;
    private javax.swing.JButton btnizquierda;
    private javax.swing.JButton btntirar;
    private javax.swing.JPanel cuadricula;
    private javax.swing.JPanel fondovidas1;
    private javax.swing.JPanel fondovidas2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldado;
    private javax.swing.JLabel lbletiquetanombre1;
    private javax.swing.JLabel lbletiquetanombre2;
    private javax.swing.JLabel lbletiquetapersonajes1;
    private javax.swing.JLabel lbletiquetapersonajes2;
    private javax.swing.JLabel lblnombrejugador1;
    private javax.swing.JLabel lblnombrejugador2;
    private javax.swing.JLabel lblturno1jug1;
    private javax.swing.JLabel lblturno1jug2;
    private javax.swing.JLabel lblturno2jug1;
    private javax.swing.JLabel lblturno2jug2;
    private javax.swing.JLabel lblturno3jug1;
    private javax.swing.JLabel lblturno3jug2;
    // End of variables declaration//GEN-END:variables
}
